"$schema" = 'https://starship.rs/config-schema.json'
add_newline = false
command_timeout = 200

format = """
[$username](bold green)\
[@](bold yellow)\
[$hostname](bold purple)\
[:](bold yellow)\
$directory\
$git_branch$git_status
$linebreak\
$character\
"""

[character]
success_symbol = "[\\$](bold cyan)"
error_symbol = "[\\$](bold red)"

[username]
show_always = true
format = "$user"

[hostname]
ssh_only = false
format = "$hostname"

[directory]
truncation_length = 0
style = "bold cyan"

[git_branch]
format = '\[[$branch]($style)'
style = "bold purple"

[git_status]
format = '[$all_status]($style)\]'
style = 'bold cyan'
ahead = '|â‡¡ ${count}'
behind = '|â‡£ ${count}'
conflicted = '|î®«'
deleted = '|ğŸ—‘ de ${count}'
diverged = '|â‡• â‡¡${ahead_count}â‡£${behind_count}'
modified = '|ğŸ“ md ${count}'
renamed = '|ğŸ‘… rn ${count}'
staged = '|ğŸ“¦ sg ${count}'
stashed = '|ğŸ“¦ st ${count}'
untracked = '|ğŸ¤· ut ${count}'
up_to_date = '|ï€Œ'
