"$schema" = 'https://starship.rs/config-schema.json'
add_newline = false
command_timeout = 200

format = """
[$username](bold green)\
[@](bold yellow)\
[$hostname](bold purple)\
[:](bold yellow)\
$directory\
$git_branch$git_status
$linebreak\
$character\
"""

[character]
success_symbol = '[ó°˜§](bold cyan)'
error_symbol = '[ó°˜§](bold red)'

[username]
show_always = true
format = '$user'

[hostname]
ssh_only = false
format = '$hostname'

[directory]
truncation_length = 0
truncate_to_repo = false
style = 'bold cyan'

[git_branch]
symbol = " îœ¥"
format = '\[[$branch$symbol]($style)'

style = "bold purple"

[git_status]
format = '[$up_to_date$conflicted$diverged$ahead$behind$modified$deleted$untracked$stashed]($style)\]'
style = 'bold cyan'
ahead = '|â‡¡ ${count}'
behind = '|â‡£ ${count}'
conflicted = '|î®«'
deleted = '|ğŸ—‘ ${count}'
diverged = '|â‡• â‡¡${ahead_count}â‡£${behind_count}'
modified = '|ï§ ${count}'
stashed = '|ó°– ${count}'
untracked = '|ğŸ¤· ${count}'
up_to_date = '|ï€Œ'
